const BASES=["http://127.0.0.1:8000","http://localhost:8000"];
let active=null,current=null,cartItems=[];
const $=id=>document.getElementById(id);
function setStatus(message,ok=true){$("status").textContent=message;$("status").className=ok?"ok":"error";}
async function api(path,options={}){let lastError=null;for(const base of BASES){try{return await fetch(base+path,options);}catch(e){lastError=e;}}throw lastError||new Error("PLG Core unavailable.");}
async function activeSisTab(){const [tab]=await browser.tabs.query({active:true,currentWindow:true});if(!tab?.id||!tab.url?.startsWith("https://sis2.cat.com/"))throw new Error("Open CAT SIS first.");return tab;}
async function send(message){const tab=await activeSisTab();try{return await browser.tabs.sendMessage(tab.id,message);}catch(e){await browser.scripting.executeScript({target:{tabId:tab.id},files:["content.js"]});return browser.tabs.sendMessage(tab.id,message);}}
async function returnToJob(jobId,partId=null){const suffix=partId?`#part-${partId}`:"";const url=`http://127.0.0.1:8000/jobs/${jobId}?refresh=${Date.now()}${suffix}`;const tabs=await browser.tabs.query({});const existing=tabs.find(t=>t.url?.includes(`/jobs/${jobId}`));if(existing?.id){await browser.tabs.update(existing.id,{url,active:true});if(existing.windowId)await browser.windows.update(existing.windowId,{focused:true});}else await browser.tabs.create({url,active:true});}
async function loadContext(){const tab=await activeSisTab();const cartMode=tab.url.includes("#/cart");$("cartMode").hidden=!cartMode;$("singleMode").hidden=cartMode;$("modeLabel").textContent=cartMode?"CAT SIS cart import":"CAT SIS verification";
 const endpoint=cartMode?"/api/active-import-job":"/api/active-verification";const response=await api(endpoint);if(!response.ok){active=null;$("jobNumber").textContent=cartMode?"No active cart import job":"No active verification";setStatus(cartMode?"Open the PLG job and click Import SIS Cart.":"Open the PLG job and click Verify Parts.",false);return;}active=await response.json();$("jobNumber").textContent=active.job_number;$("customer").textContent=`Customer: ${active.customer}`;$("machine").textContent=`Machine: ${active.manufacturer} ${active.machine}`;$("pin").textContent=`PIN / Serial: ${active.pin_serial}`;$("requestedPart").textContent=active.requested_description?`Requested part: ${active.requested_description}`:"";setStatus("PLG job loaded.");}
async function readPart(){setStatus("Reading current SIS part…");const r=await send({type:"PLG_READ_SIS_PART"});if(!r?.ok){current=null;setStatus(r?.status||"Could not read SIS part.",false);return;}current=r;$("partNumber").textContent=r.oem_part_number;$("description").textContent=r.oem_description;$("price").textContent=r.oem_dealer_price!=null?`Price: $${Number(r.oem_dealer_price).toFixed(2)} USD`:"Price: not detected";$("availability").textContent=`Availability: ${r.oem_dealer_availability||"not detected"}`;setStatus("Review, then import.");}
function renderCart(){$("cartCount").textContent=`${cartItems.length} cart item${cartItems.length===1?"":"s"}`;$("cartItems").innerHTML=cartItems.map(item=>`<div class="cart-row"><strong>${item.oem_part_number}</strong><span class="amount">${item.oem_price!=null?`$${Number(item.oem_price).toFixed(2)}`:"No price"}</span><span>${item.oem_description} · Qty ${item.quantity} · ${item.availability||"Availability unknown"}</span></div>`).join("");}
async function readCart(){setStatus("Reading SIS cart…");const r=await send({type:"PLG_READ_SIS_CART"});if(!r?.ok){cartItems=[];setStatus(r?.status||"Could not read SIS cart.",false);return;}cartItems=r.items||[];renderCart();setStatus("Review the cart items, then import all.");}
$("readPart").onclick=readPart;
$("importPart").onclick=async()=>{if(!active)return setStatus("No active verification.",false);if(!current){await readPart();if(!current)return;}const response=await api("/api/capture-part",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({part_id:active.part_id,oem_part_number:current.oem_part_number,oem_description:current.oem_description,diagram_name:"",callout_number:"",source_url:current.source_url,diagram_url:current.diagram_url,product_url:current.product_url,oem_dealer_name:current.oem_dealer_name,oem_dealer_price:current.oem_dealer_price,oem_dealer_availability:current.oem_dealer_availability,oem_dealer_lead_time:current.oem_dealer_lead_time,verification_source:current.verification_source,verification_notes:"Imported from CAT SIS."})});const data=await response.json();if(!response.ok)return setStatus(data.detail||"Import failed.",false);setStatus("Imported. Returning to PLG…");await returnToJob(data.job_id,data.part_id);};
$("readCart").onclick=readCart;
$("importCart").onclick=async()=>{if(!active)return setStatus("No active cart import job.",false);if(!cartItems.length){await readCart();if(!cartItems.length)return;}const response=await api("/api/import-sis-cart",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job_id:active.job_id,items:cartItems})});const data=await response.json();if(!response.ok)return setStatus(data.detail||"Cart import failed.",false);setStatus(`${data.imported_count} SIS cart items imported. Returning to PLG…`);await returnToJob(data.job_id);};
loadContext().catch(e=>setStatus(e.message,false));
