const BASE=["http://127.0.0.1:8000","http://localhost:8000"];let active=null,current=null;const $=id=>document.getElementById(id);
function msg(t,ok=true){$("status").textContent=t;$("status").className=ok?"ok":"error";}
async function api(path,opt={}){for(const b of BASE){try{return await fetch(b+path,opt)}catch(e){}}throw new Error("PLG Core unavailable.");}
async function cat(m){const [t]=await browser.tabs.query({active:true,currentWindow:true});if(!t?.id||!t.url?.startsWith("https://parts.cat.com/"))throw new Error("Open CAT Parts first.");try{return await browser.tabs.sendMessage(t.id,m)}catch(e){await browser.scripting.executeScript({target:{tabId:t.id},files:["content.js"]});return browser.tabs.sendMessage(t.id,m)}}
async function refresh(){msg("Loading active PLG verification…");const r=await api("/api/active-verification");if(!r.ok){active=null;$("jobNumber").textContent="No active verification";msg("Click Verify in CAT from PLG.",false);return}active=await r.json();$("jobNumber").textContent=active.job_number;$("customer").textContent=`Customer: ${active.customer}`;$("machine").textContent=`Machine: ${active.manufacturer} ${active.machine}`;$("pin").textContent=`PIN: ${active.pin_serial}`;$("requestedPart").textContent=`Part: ${active.requested_description}`;msg("Active PLG verification loaded.");}
async function inspect(){msg("Reading current CAT product…");const r=await cat({type:"PLG_EXTRACT_CURRENT_PRODUCT"});if(!r?.ok){current=null;msg(r?.status||"Could not read product.",false);return}current=r;$("currentPart").textContent=r.oem_part_number;$("currentDescription").textContent=r.oem_description;$("dealerName").textContent=`Dealer: ${r.oem_dealer_name||"not detected"}`;$("dealerPrice").textContent=r.oem_dealer_price!=null?`Price: $${Number(r.oem_dealer_price).toFixed(2)} USD`:"Price: not detected";$("availability").textContent=`Availability: ${r.oem_dealer_availability||"not detected"}`;$("leadTime").textContent=`Lead time: ${r.oem_dealer_lead_time||"not detected"}`;$("diagramStatus").textContent=r.diagram_url?"Machine-specific diagram URL recorded.":"No diagram URL recorded.";msg("Review the detected information, then import.");}
$("refreshJob").onclick=refresh;
$("loadMachine").onclick=async()=>{if(!active)return msg("No active verification.",false);const r=await cat({type:"PLG_LOAD_PIN",pin:active.pin_serial});msg(r?.status||"PIN submitted.",Boolean(r?.ok));};
$("inspectCurrent").onclick=inspect;
$("captureCurrent").onclick=async()=>{if(!active)return msg("No active verification.",false);if(!current){await inspect();if(!current)return}const r=await api("/api/capture-part",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({part_id:active.part_id,oem_part_number:current.oem_part_number,oem_description:current.oem_description,diagram_name:"",callout_number:"",source_url:current.product_url,diagram_url:current.diagram_url,product_url:current.product_url,oem_dealer_name:current.oem_dealer_name,oem_dealer_price:current.oem_dealer_price,oem_dealer_availability:current.oem_dealer_availability,oem_dealer_lead_time:current.oem_dealer_lead_time,verification_notes:"Imported from CAT product page."})});const d=await r.json();if(!r.ok)return msg(d.detail||"Import failed.",false);msg("CAT part and OEM dealer information imported.");active=null;};
refresh();